version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9:latest
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - python3
    - python3-pip
    - openssh-clients
    - crypto-policies
    - crypto-policies-scripts
  python:
    - ansible
    - ansible-runner
additional_build_steps:
  append_final:
    - RUN update-crypto-policies --set DEFAULT:PQ
options:
  package_manager_path: /usr/bin/microdnf
  tags:
    - pqc-ee-rhel9:1.0
