# DOES NOT WORK ATM.
version: 3
images:
  base_image:
    name: registry.access.redhat.com/ubi9:latest
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - python3
    - python3-pip
    - openssh-clients
    - crypto-policies
    - crypto-policies-scripts
  python:
    - ansible
    - ansible-runner
additional_build_steps:
  prepend_base:
    - COPY openssh.config-rhel9 /etc/crypto-policies/back-ends/
  append_final:
    - RUN update-crypto-policies --set DEFAULT:PQ
options:
  package_manager_path: /usr/bin/dnf
  tags:
    - pqc-ee-rhel9:1.1
